# Generated by Django 5.2.6 on 2025-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Veículo')),
                ('brand', models.CharField(choices=[('TOYOTA', 'Toyota'), ('BYD', 'BYD')], max_length=20, verbose_name='Marca')),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback')], max_length=20, verbose_name='Tipo de Carroceria')),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Quantidade Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'vehicles',
            },
        ),
    ]
