# Generated by Django 5.2.6 on 2025-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do veículo (formatos: JPG, PNG, etc.)', null=True, upload_to='vehicles/', verbose_name='Imagem do Veículo'),
        ),
    ]
