# Generated by Django 5.2.6 on 2025-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Se este dealer aparece na lista pública para clientes', verbose_name='Disponível Publicamente'),
        ),
    ]
