# Generated by Django 5.2.6 on 2025-10-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_dealer_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, verbose_name='Gênero')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Mensal')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('purchase_code', models.CharField(max_length=10, unique=True, verbose_name='Código da Compra')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.dealer', verbose_name='Concessionária')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehicle', verbose_name='Veículo Comprado')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
