# Generated by Django 5.2.6 on 2025-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rua'),
        ),
    ]
